blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://mypdns.org/spirillen/phishing/-/issues
    about: Answers to questions and other kinds of help support is provided on the My Privacy DNS support forum
